print("OPERACIONES")
num1 = int(input("Escribe el nº1: "))
num2 = int(input("Escribe el nº2: "))
print(f"{num1} + {num2} = {num1+num2}")
print(f"{num1} * {num2} = {num1*num2}")
print(f"{num1} / {num2} = {num1/num2}")
