print("REGISTRO DEL ALUMNADO DEL IES ORRIOLS")
print("****************************************")
print()
print()
print("MENÚ PRINCIPAL")
print("_________________________")
print("1. INTRODUCCIÓN DE DATOS")
print("2. MOSTRAR DATOS DE TODOS LOS ALUMNOS")
print("3. MOSTRAR DATOS DE UN ALUMNO (NIA)")
print("4. ESTADÍSTICAS. mostrar la nota media de un alumno")
print("5. SALIR")
